set :domain, 's3.mydevil.net'
set :deploy_to, '/home/media30/domains/apki.org'
set :repository, 'https://github.com/media3-0/apki.org.git'
set :branch, 'release'
set :user, 'media30'
set :rails_env, 'production'
